### PR TITLE
Fix #60: feat: support per-request executor overrides for orchestrated send_message

### LINKED ISSUE #60: feat: support per-request executor overrides for orchestrated send_message
## Summary

`agent-harness` has pluggable executors at the provider level, but the public orchestration path (`AgentHarness.send_message` / `Conductor` / `ProviderManager`) is still effectively tied to the globally configured `config.command_executor`.

That makes it hard for apps to use `agent-harness` for per-request container execution, where each request may need a different executor instance.

## Current Limitation

In 0.5.6:

- `Providers::Base` supports an injected `executor:`
- `ProviderManager#create_provider` always constructs providers with `executor: @config.command_executor`
- provider instances are cached in `@provider_instances`
- `AgentHarness.send_message` and `Conductor#send_message` do not accept an executor override

So apps with one container per job/run cannot cleanly do:

```ruby
AgentHarness.send_message(prompt, provider: :codex, executor: executor_for_this_run)
```

while still keeping orchestration, fallback, retries, and provider selection inside `agent-harness`.

## Why This Matters

Paid runs each agent job in its own Docker container. The app wants to route execution through `agent-harness` instead of building provider CLI commands itself, but each run needs a different container-backed executor.

Today, the lack of a per-request executor path forces Paid's `RunAgentActivity` to bypass `AgentHarness.send_message` and shell out directly inside the container.

## Expected Behavior

`agent-harness` should support a per-request executor override for orchestrated execution.

Examples:

```ruby
AgentHarness.send_message(
  prompt,
  provider: :claude,
  executor: custom_executor
)
```

or some equivalent execution-context object that can be threaded through `Conductor`/`ProviderManager` without mutating global config.

## Notes

A clean solution probably needs to avoid reusing cached provider instances with the wrong executor, or create request-scoped provider instances when an executor override is present.

### PR DESCRIPTION
**Pull request by viamin**
Implemented per-request executor overrides through the orchestration path and committed it as `58a0cd7` (`Add per-request executor overrides to orchestration`).

`AgentHarness.send_message` and `Conductor` now accept `executor:` and thread it through provider selection, direct execution, and fallback switching. `ProviderManager` keeps using cached provider instances for the default global executor, but creates request-scoped provider instances whenever an override is supplied so executors do not bleed across requests.

Verification: `bundle exec rubocop` passed, `bundle exec rspec` passed, and the git worktree is clean.

---

Closes #60

### CODE REVIEW

**Review by viamin — COMMENTED** [review]
I found one regression in the new per-request executor override path. The PR is otherwise scoped to issue #60 and threads the override through the intended entry points, but fallback during an overridden request still mutates global provider selection state.

**Comment by viamin** [comment]
## Agent Update

Resolved the review thread by making fallback selection explicit about the failing provider. [`Conductor`]( /workspace/lib/agent_harness/orchestration/conductor.rb#L157 ) now passes `from: provider_name` into [`ProviderManager#switch_provider`]( /workspace/lib/agent_harness/orchestration/provider_manager.rb#L76 ), and `switch_provider` uses that provider to derive the fallback chain instead of `@current_provider`. That fixes the request-scoped executor case where the active global provider and the failing per-request provider differ.

I also added a regression spec in [`provider_manager_spec.rb`]( /workspace/spec/agent_harness/orchestration/provider_manager_spec.rb#L296 ) covering the reviewer’s scenario: after a global switch has moved `current_provider`, a request-scoped failover from `:claude` still uses `:claude`’s chain, preserves the override executor, and leaves the global provider unchanged.

Verification passed with `bundle install --path vendor/bundle`, `bundle exec rubocop`, and `bundle exec rspec`. Commit: `143147b` (`Fix request-scoped provider fallback origin`). Worktree is clean.

File: lib/agent_harness/orchestration/provider_manager.rb [hunk 1]
```diff
@@ -30,49 +30,57 @@ def initialize(config)
...
       # @return [Providers::Base] selected provider instance
       # @raise [NoProvidersAvailableError] if no providers available
-      def select_provider(preferred = nil)
+      def select_provider(preferred = nil, executor: nil)
         preferred ||= @current_provider
 
         # Check circuit breaker
         if circuit_open?(preferred)
-          return select_fallback(preferred, reason: :circuit_open)
+          return select_fallback(preferred, reason: :circuit_open, executor: executor)
```
Comment (viamin) [inline lib/agent_harness/orchestration/provider_manager.rb]: Because `executor:` creates a request-scoped provider instance, this path is still mixing request-scoped execution with process-global health state. If the default `:claude` executor tripped the circuit breaker earlier, a fresh override executor will still be forced onto the fallback provider here, which defeats the use case in #60. I think override-backed requests need to bypass the shared circuit/rate-limit/health gates entirely, or those gates need to be keyed by executor as well. A minimal fix here would be:

```suggestion
        return get_provider(preferred, executor: executor) if executor

        # Check circuit breaker
        if circuit_open?(preferred)
          return select_fallback(preferred, reason: :circuit_open, executor: executor)
        end
```

**Review by viamin — COMMENTED** [review]
I found one correctness issue in the new request-scoped executor path. `ProviderManager#select_provider` still consults the shared circuit-breaker / rate-limit / health state even when `executor:` is present, so an override-backed request can be forced onto a fallback provider because of failures from an unrelated global executor. That breaks the per-request isolation this PR is trying to add.

**Comment by viamin** [comment]
## Agent Update

Updated the review-blocking behavior in [provider_manager.rb](/workspace/lib/agent_harness/orchestration/provider_manager.rb): `executor:` now remains request-scoped for provider construction, but `select_provider` and fallback selection still honor the normal circuit-breaker, rate-limit, and health gates. That keeps the earlier request-local fallback fixes (`from:` origin handling and no global switch state for override-backed failover) while resolving the reviewer’s concern that orchestration guarantees were being skipped.

I updated [provider_manager_spec.rb](/workspace/spec/agent_harness/orchestration/provider_manager_spec.rb) to cover the corrected semantics: healthy override-backed selection still uses the supplied executor, unhealthy preferred providers fall back through eligible providers with the override preserved, and request-scoped failover now raises when no healthy fallback is available.

Verification passed with `bundle install --path vendor/bundle`, `bundle exec rubocop`, and `bundle exec rspec` (`844 examples, 0 failures`). Commit: `13c2f1c` (`Preserve orchestration gates for executor overrides`). Worktree is clean.

**Comment by viamin** [comment]
## Agent Update

Addressed the unresolved conductor review and committed it as `5bdf2d2` (`Carry switched provider through conductor retries`).

The fix is in [conductor.rb](/workspace/lib/agent_harness/orchestration/conductor.rb): switch-handling now returns the fallback provider name and the retry loop carries that forward, so executor-scoped failover retries re-enter selection with the switched provider instead of the original failing one. I added a regression spec in [conductor_send_message_spec.rb](/workspace/spec/agent_harness/orchestration/conductor_send_message_spec.rb) covering the reviewer’s exact path: a request-scoped rate-limit switch retries through the fallback provider with the override preserved.

Verification passed:
- `bundle install --path vendor/bundle`
- `bundle exec rubocop`
- `bundle exec rspec`
- pre-commit hook passed during `git commit`


Worktree is clean.

**Review by viamin — COMMENTED** [review]
I did not find any blocking issues in the patch. The executor override is threaded through `AgentHarness.send_message`, `Conductor`, and `ProviderManager`, request-scoped providers are no longer cached, and the request-scoped failover path now preserves the override without mutating the global current provider, which matches the behavior described in #60.

Residual risk: I could not rerun the focused specs in this environment because `bundle exec rspec` failed with `bundler: command not found: rspec`, so this review is based on code inspection rather than local execution.

**Comment by viamin** [comment]
This PR was automatically merged by paid's auto-merge feature.
